TimeMachine/Controllers/GroupExpenseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Globalization;
using TimeMachine.Models;
using TimeMachine.BaseCode;
using RestSharp;

namespace TimeMachine.Controllers
{
    [Authorize]
    public class GroupExpenseController : Controller
    {
        ApplicationDbContext dbContext = null;

        public GroupExpenseController()
        {
            dbContext = new ApplicationDbContext();
        }

        // GET: GroupExpense
        public ActionResult Index()
        {
            List<SelectListItem> list = new List<SelectListItem>();

            // Find GroupId of particular user
            var GroupIds = dbContext.TbGroupUser.Where(
                t => t.UserId.Equals(
                    dbContext.Users.FirstOrDefault(u => u.UserName.Equals(User.Identity.Name)).Id
                    )
                ).Select(t => t.GroupId);

            // Find GroupNames of particular user
            foreach (int grpId in GroupIds)
            {
                list.Add(
                    new SelectListItem()
                    {
                        Text = dbContext.TbGroup.FirstOrDefault(t => t.GroupId.Equals(grpId)).GroupName,
                        Value = grpId.ToString()
                    });
            };

            GroupIndexViewModel model = new GroupIndexViewModel()
            {
                GroupsList = list,
                CreateGroupVM = new CreateGroupViewModel()
            };

            return View(model);
        }

        [HttpPost]
        public ActionResult CreateGroup(CreateGroupViewModel model)
        {
            if (ModelState.IsValid)
            {
                //Making the Group
                Group GroupRow = new Group();
                GroupRow.GroupName = model.GroupName;
                GroupRow.StartAmount = model.Amount;
                GroupRow.AmountLeft = model.Amount;
                GroupRow.StartDate = Convert.ToDateTime(model.StartDate, new CultureInfo("es-ES"));
                GroupRow.EndDate = Convert.ToDateTime(model.EndDate, new CultureInfo("es-ES"));
                GroupRow.LastUpdated = DateTime.Now;
                dbContext.TbGroup.Add(GroupRow);
                dbContext.SaveChanges();

                int NewGroupId = GroupRow.GroupId;

                //Add Data in Group user table
                GroupUser GroupUserRow = new GroupUser();
                GroupUserRow.GroupId = NewGroupId;
                GroupUserRow.UserId = dbContext.Users.FirstOrDefault(t => t.UserName.Equals(User.Identity.Name)).Id;
                GroupUserRow.Role = 1; //For Admin
                dbContext.TbGroupUser.Add(GroupUserRow);
                dbContext.SaveChanges();

                //Save GroupId in Session
                TempData["GroupId"] = NewGroupId;

                //Save GroupId in Session
                //if (Session["GroupId"] == null)
                //{
                //    Session["GroupId"] = NewGroupId;
                //}

                return RedirectToAction("GroupInfo");
            }
            else
            {
                return View("Index");
            }
        }

        [HttpGet]
        public ActionResult GroupInfo(int GroupId)
        {
            IList<SelectListItem> categoryList = new List<SelectListItem>();
            categoryList.Add(new SelectListItem(){
                Text = "Food",
                Value = "1",
                Selected = true
            });
            categoryList.Add(new SelectListItem(){
                Text = "Shopping",
                Value = "2"
            });
            categoryList.Add(new SelectListItem(){
                Text = "General",
                Value = "3"
            });

            if (TempData["GroupId"] == null)
            {
                TempData["GroupId"] = GroupId;
            }

            var userIds = dbContext.TbGroupUser.Where(t => t.GroupId.Equals(GroupId)).Select(t => t.UserId);
            List<SelectListItem> usersList = new List<SelectListItem>();

            foreach(string id in userIds)
            {
                usersList.Add(new SelectListItem()
                {
                    Text = dbContext.Users.Find(id).FirstName,
                    Value = id
                });
            }

            GroupInfoViewModel GroupTransactionVM = new GroupInfoViewModel()
            {
                CreateGroupTransactionVM = new GroupTransactionViewModel()
                {
                    CategoryList = categoryList,
                    GroupUsers = usersList
                },
                GroupInvitationForm = new GroupInvitation(),
                GroupUsersList = usersList,
                GroupTransactionHistoryDateVM = new GroupTransactionHistoryDateViewModel()
            };

            return View(GroupTransactionVM);
        }

        [HttpPost]
        public ActionResult SaveGroupTransaction(GroupTransactionViewModel model)
        {
            GroupTransaction transactionData = null;
            int GroupId = Convert.ToInt32(TempData.Peek("GroupId"));
            if (ModelState.IsValid)
            {
                transactionData = new GroupTransaction()
                {
                    Id = Guid.NewGuid(),
                    GroupId = GroupId,
                    Date = Convert.ToDateTime(model.Date),
                    ItemName = model.ItemName,
                    ItemPrice = model.ItemPrice,
                    ItemType = model.ItemType,
                    Quantity = model.Quantity,
                    LastUpdatedDate = DateTime.Now,
                    SpentByUserId = model.SpentUser.ToString(),
                    UpdatedByUserId = dbContext.Users.FirstOrDefault(t => t.UserName.Equals(User.Identity.Name)).Id,
                    Comments = model.Comments,
                    NewTransactionId = String.Empty
                };
                dbContext.TbGroupTransactions.Add(transactionData);
                dbContext.SaveChanges();
            }
            return RedirectToAction("GroupInfo", new { GroupId = GroupId });
        }

        [HttpGet]
        public ActionResult ViewGroupTransactionHistory()
        {
            return View("GroupTransactionHistoryDatePage");
            //GroupTransactionHistoryViewModel ViewGrpTransHistoryVM = null;
            //int groupId = Convert.ToInt32(TempData.Peek("GroupId"));

            ////Getting Data from Transaction Table
            //var transactionHistory = dbContext.TbGroupTransactions.Where(t => t.GroupId.Equals(groupId)).OrderByDescending(t => t.LastUpdatedDate);
            //List<ViewGroupTransactionViewModel> ViewGrpTransVM = new List<ViewGroupTransactionViewModel>();
            //ViewGroupTransactionViewModel viewModel = null;

            ////Adding rows to transaction history view model 
            //foreach (var row in transactionHistory)
            //{
            //    viewModel = new ViewGroupTransactionViewModel();
            //    viewModel.Date = row.Date;
            //    viewModel.Id = row.Id;
            //    viewModel.ItemName = row.ItemName;
            //    viewModel.ItemPrice = row.ItemPrice;
            //    viewModel.Quantity = row.Quantity;
            //    viewModel.Comments = row.Comments;
            //    viewModel.SpentByUser = dbContext.Users.Find(row.SpentByUserId).FirstName + " " + dbContext.Users.Find(row.SpentByUserId).LastName;
            //    ViewGrpTransVM.Add(viewModel);
            //}

            //ViewGrpTransHistoryVM = new GroupTransactionHistoryViewModel()
            //{
            //    GroupName = dbContext.TbGroup.Find(groupId).GroupName,
            //    ViewTransactionHistoryVM = ViewGrpTransVM
            //};

            //return View(ViewGrpTransHistoryVM);
        } 

        public static void SendSimpleMessage()
        {
            RestClient client = new RestClient();
            client.BaseUrl = new Uri("https://api.mailgun.net/v3");
            client.Authenticator =
                   new HttpBasicAuthenticator("api",
                                              "key-6de7390c50abada1b301c00207a3be35");
            RestRequest request = new RestRequest();
            request.AddParameter("domain",
                                "sandboxa39a1e82a3b14174a1eb4c8ccd6b3082.mailgun.org", ParameterType.UrlSegment);
            request.Resource = "{domain}/messages";
            request.AddParameter("from", "Mailgun Sandbox <postmaster@sandboxa39a1e82a3b14174a1eb4c8ccd6b3082.mailgun.org>");
            request.AddParameter("to", "Ambuj Sharma <ambujsharma23@gmail.com>");
            request.AddParameter("subject", "Hello Ambuj Sharma");
            request.AddParameter("text", "Congratulations Ambuj Sharma, you just sent an email with Mailgun!  You are truly awesome!  You can see a record of this email in your logs: https://mailgun.com/cp/log .  You can send up to 300 emails/day from this sandbox server.  Next, you should add your own domain so you can send 10,000 emails/month for free.");
            request.Method = Method.POST;
            client.Execute(request);
        }
    }
}

TimeMachine/Views/GroupExpense/CreateGroup.cshtml
@model TimeMachine.Models.CreateGroupViewModel

@using (Html.BeginForm("CreateGroup","GroupExpense")) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.GroupName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GroupName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GroupName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control bt-datepicker" } })
                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control bt-datepicker" } })
                @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

TimeMachine/Views/GroupExpense/CreateGroupTransaction.cshtml
@model TimeMachine.Models.GroupTransactionViewModel

@using (Html.BeginForm("SaveGroupTransaction", "GroupExpense", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(false)


    <div class="form-group">
        @Html.LabelFor(m => m.SpentUser, new { @class = "col-md-4 control-label" })
        <div class="col-md-8">
            @Html.DropDownListFor(m => m.SpentUser, Model.GroupUsers, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.SpentUser, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Date, new { @class = "col-md-4 control-label" })
        <div class="col-md-8">
            @Html.TextBoxFor(m => m.Date, new { @class = "form-control bt-datetimepicker" })
            @Html.ValidationMessageFor(m => m.Date, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.ItemType, new { @class = "col-md-4 control-label" })
        <div class="col-md-8">
            @Html.DropDownListFor(m => m.ItemType, Model.CategoryList, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.ItemType, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.ItemName, new { @class = "col-md-4 control-label" })
        <div class="col-md-8">
            @Html.TextBoxFor(m => m.ItemName, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.ItemName, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Quantity, new { @class = "col-md-4 control-label" })
        <div class="col-md-8">
            @Html.TextBoxFor(m => m.Quantity, new { @class = "form-control", type = "number" })
            @Html.ValidationMessageFor(m => m.Quantity, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.ItemPrice, new { @class = "col-md-4 control-label" })
        <div class="col-md-8">
            @Html.TextBoxFor(m => m.ItemPrice, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.ItemPrice, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Comments, new { @class = "col-md-4 control-label" })
        <div class="col-md-8">
            @Html.TextBoxFor(m => m.Comments, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Comments, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-4 col-md-4">
            <input type="submit" class="btn btn-primary" value="Save" />
        </div>
    </div>
}

TimeMachine/Views/GroupExpense/EditGroup.cshtml
@model TimeMachine.Models.CreateGroupViewModel

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CreateGroupViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.GroupName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GroupName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GroupName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control bt-datepicker" } })
                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control bt-datepicker" } })
                @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

TimeMachine/Views/GroupExpense/GroupInfo.cshtml
@model TimeMachine.Models.GroupInfoViewModel

@{
    ViewBag.Title = "GroupInfo";
}

<div class="jumbotron text-center">
    <h2>View Group Info</h2>
</div>

<div class="row">

    <section class="col-md-7">
        <div id="AddGrpTransaction">
            <h3>Make A Transaction</h3>
            <hr />
            @Html.Partial("CreateGroupTransaction", Model.CreateGroupTransactionVM)
        </div>
    </section>

    <section class="col-md-5">

        <div id="ViewGrpTransaction">
            <h3>View Transaction History</h3>
            <hr />
            @Html.Partial("GroupTransactionHistoryDatePage",Model.GroupTransactionHistoryDateVM)
            @*<a href="ViewGroupTransactionHistory" class="btn-link col-md-offset-4">Click Here</a>*@
            @*@Html.ActionLink("Click Here", "ViewTransactionHistory", "", htmlAttributes: new { @class = "btn-link col-md-offset-4" })*@
        </div>

        <div id="GrpMemberLists">
            <h3>Group Members</h3>
            <hr />
            <div class="list-group">
                <div class="">
                    <div class="list-group-item col-md-12">Test</div>
                </div>
                @foreach (var item in Model.GroupUsersList)
                {
                    <div class="list-group-item">@item.Text</div>
                }
            </div>
        </div>

        <div id="GrpInvite">
            <h3>Add Group Members</h3>
            <hr />
            @using (Ajax.BeginForm("A", "C", new AjaxOptions()
            {
                HttpMethod = "GET",
                OnSuccess = "SuccessInvite",
                OnFailure = "ErrorInvite"
            }))
            {
                <div class="form-group">
                    @Html.LabelFor(m => m.EmailId, htmlAttributes: new { @class = "control-label" })
                    <div>
                        @Html.TextBoxFor(m => m.EmailId, htmlAttributes: new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    <input type="button" class="btn btn-primary" value="Send Invite" />
                </div>
            }
        </div>

    </section>
</div>

@section scripts{
    <script type="text/javascript">
        (function () {
            $("#StartDatePicker").datetimepicker();
            $("#EndDatePicker").datetimepicker();

            $("#StartDatePicker").on("dp.change", function (e) {
                $("#EndDatePicker").data("DateTimePicker").minDate(e.date);
            });

            $("#EndDatePicker").on("dp.change", function (e) {
                $("#StartDatePicker").data("DateTimePicker").maxDate(e.date);
            });

        }());
    </script>
}

TimeMachine/Views/GroupExpense/GroupTransactionHistoryDatePage.cshtml
@model TimeMachine.Models.GroupTransactionHistoryDateViewModel

@using (Html.BeginForm("a", "c", FormMethod.Get))
{
    @Html.AntiForgeryToken()

    <div class="form-group">
        @Html.LabelFor(m => m.StartDate, htmlAttributes: new { @class = "control-label" })
        <div class="input-group date" id="StartDatePicker">
            @Html.TextBoxFor(m => m.StartDate, htmlAttributes: new { @class = "form-control mapp-datefield" })
            <span class="input-group-addon">
                <span class="glyphicon glyphicon-calendar"></span>
            </span>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.EndDate, htmlAttributes: new { @class = "control-label " })
        <div class="input-group date" id="EndDatePicker">
            @Html.TextBoxFor(m => m.EndDate, htmlAttributes: new { @class = "form-control mapp-datefield" })
            <span class="input-group-addon">
                <span class="glyphicon glyphicon-calendar"></span>
            </span>
        </div>
    </div>

    <div class="col-md-offset-5">
        <input type="submit" class="btn btn-primary" />
    </div>
}

TimeMachine/Views/GroupExpense/Index.cshtml
@model TimeMachine.Models.GroupIndexViewModel
@{
    ViewBag.Title = "Index";
}

<div class="jumbotron text-center">
    <h2>Manage Your Groups Expenses</h2>
    <p class="lead">(Make unlimited groups and record multiple transactions)</p>
</div>


<div class="row">
    <div class="col-md-6">
        <h4>Create New Group</h4>
        <hr/>
       @Html.Partial("CreateGroup",Model.CreateGroupVM)
    </div>

    <div class="col-md-6">
        <h4>View Your Groups</h4>
        <hr/>
        @using (Html.BeginForm("GroupInfo", "GroupExpense", FormMethod.Get))
        {
            <div class="form-group">
                @Html.Label("Select Group", htmlAttributes: new { @class = "control-label" })
                <div>
                    @Html.DropDownList("GroupId", Model.GroupsList, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessage("GroupId", htmlAttributes: new { @class = "text-danger" })
                </div>
            </div>
            
            <div class="form-group">
                <input type="submit" class="btn btn-primary" />
            </div> 
        }
    </div>
</div>

TimeMachine/Views/GroupExpense/ViewGroupTransactionHistory.cshtml
@model TimeMachine.Models.GroupTransactionHistoryViewModel

@{
    ViewBag.Title = "ViewTransactionHistory";
}

<div class="jumbotron text-center">
    <h2>ViewGroupTransactionHistory</h2>
</div>

<div class="row">
    <h2 class="text-center">View Transactions Of Group @Model.GroupName</h2>
    <table class="table table-bordered table-responsive table-hover">
        <thead>
            <tr>
                <th>Date</th>
                <th>Item Name</th>
                <th>Item Quantity</th>
                <th>Total Price</th>
                <th>Comments</th>
                <th>Spent By</th>
                <th>Edit</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
            @foreach(var Item in Model.ViewTransactionHistoryVM)
            {
                <tr>
                    <td>@Item.Date</td>
                    <td>@Item.ItemName</td>
                    <td>@Item.Quantity</td>
                    <td>@Item.ItemPrice</td>
                    <td>@Item.Comments</td>
                    <td>@Item.SpentByUser</td>
                    <td>@Html.ActionLink("Edit", "EditGroupTransactionHistory", new { transId = @Item.Id }, htmlAttributes: new { @class = "btn-link" })</td>
                    <td>@Html.ActionLink("Delete", "DeleteGroupTransactionHistory", new { transId = @Item.Id }, htmlAttributes: new { @class = "btn-link" })</td>
                </tr>
            }
        </tbody>
    </table>
</div>