TimeMachine/Controllers/IndividualExpenseController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TimeMachine.Models;

namespace TimeMachine.Controllers
{
    [Authorize]
    public class IndividualExpenseController : Controller
    {
        ApplicationDbContext dbContext = null;

        public IndividualExpenseController()
        {
            dbContext = new ApplicationDbContext();
        }

        // GET: IndividualExpense
        public ActionResult Index()
        {
            TempData["HeaderText"] = "Record Your Expenditure";
            TempData["IndividualExpenseActionType"] = "INSERT";

            IndividualExpenseDetailViewModel IndividualExpenseDetailVM = new IndividualExpenseDetailViewModel()
            {
                IndividualExpenseFormModel = new IndividualExpenseModel(),
                IndividualExpenseHistoryModel = dbContext.TbIndividualExpense.ToList().Where(t=>t.UserName == User.Identity.Name)
                                                         .OrderByDescending(t=>t.Date).OrderByDescending(t=>t.LastUpdated),
                CategoryList = GetCategoryList()
            };

            return View(IndividualExpenseDetailVM);
        }

        [HttpPost]
        public ActionResult SaveExpenseForm(IndividualExpenseDetailViewModel IndExpVM)
        {
            IndividualExpenseModel model = new IndividualExpenseModel();
            model.Id = IndExpVM.IndividualExpenseFormModel.Id;
            model.Date = IndExpVM.IndividualExpenseFormModel.Date;
            model.Category = IndExpVM.IndividualExpenseFormModel.Category;
            model.ItemName = IndExpVM.IndividualExpenseFormModel.ItemName;
            model.ItemPrice = IndExpVM.IndividualExpenseFormModel.ItemPrice;
            model.Notes = IndExpVM.IndividualExpenseFormModel.Notes;
            model.LastUpdated = DateTime.Now;
            model.UserName = User.Identity.Name;
            
            if(ModelState.IsValid)
            {
                if (TempData["IndividualExpenseActionType"].ToString() == "INSERT")
                {
                    dbContext.TbIndividualExpense.Add(model);
                    dbContext.SaveChanges();
                }
                else if (TempData["IndividualExpenseActionType"].ToString() == "UPDATE")
                {
                    dbContext.Entry(model).State = System.Data.Entity.EntityState.Modified;
                    dbContext.SaveChanges();
                }
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        [HttpGet]
        public ActionResult EditHistoryItem(int Id)
        {
            TempData["HeaderText"] = "Edit History Item";
            TempData["IndividualExpenseActionType"] = "UPDATE";

            IndividualExpenseDetailViewModel IndividualExpenseDetailVM = new IndividualExpenseDetailViewModel()
            {
                IndividualExpenseFormModel = dbContext.TbIndividualExpense.Find(Id),
                IndividualExpenseHistoryModel = null,
                CategoryList = GetCategoryList()
            };
            return View("EditHistoryItem",IndividualExpenseDetailVM);
        }

        [HttpGet]
        public ActionResult DeleteHistoryItem(int Id)
        {
            var model = dbContext.TbIndividualExpense.Find(Id);
            dbContext.TbIndividualExpense.Remove(model);
            dbContext.SaveChanges();

            return RedirectToAction("Index");
        }

        private IList<SelectListItem> GetCategoryList()
        {
            IList<SelectListItem> CategoryList = new List<SelectListItem>();
            CategoryList.Add(new SelectListItem
            {
                Text = "Food",
                Value = "1",
                Selected = true,
            });
            CategoryList.Add(new SelectListItem
            {
                Text = "Household",
                Value = "2"
            });

            return CategoryList;
        }
    }
}

TimeMachine/Views/IndividualExpense/EditHistoryItem.cshtml
@{
    ViewBag.Title = "Individual Expense Details";
}

<div class="container">
    <div class="jumbotron text-center">
        <h2>@ViewBag.Title</h2>
        <p class="lead">Manage Your Personal Account</p>
    </div>
</div>


<div class="container">
    <div class="row">
        <div class="col-md-12">
            @Html.Partial("IndividualExpenseForm")
        </div>
    </div>
</div>

TimeMachine/Views/IndividualExpense/Index.cshtml
@{
    ViewBag.Title = "Individual Expense Details";
}

<div class="container">
    <div class="jumbotron text-center">
        <h2>@ViewBag.Title</h2>
        <p class="lead">Manage Your Personal Account</p>
    </div>
</div>


<div class="container">
    <div class="row">
        <div class="col-md-4">
            @Html.Partial("IndividualExpenseForm")
        </div>

        <div class="col-md-8">
            @Html.Partial("ViewExpenseHistory")
        </div>
    </div>
</div>

TimeMachine/Views/IndividualExpense/IndividualExpenseForm.cshtml
@model TimeMachine.Models.IndividualExpenseDetailViewModel

@using (Html.BeginForm("SaveExpenseForm", "IndividualExpense", FormMethod.Post, new { @class="form-horizontal", role="form" }))
{ 
    @Html.AntiForgeryToken()
    
    <h4>@TempData["HeaderText"]</h4>
    <hr/>
    
    @Html.ValidationSummary("", new { @class = "text-danger" })
    
    @Html.HiddenFor(m => m.IndividualExpenseFormModel.Id, new { @Value = Model.IndividualExpenseFormModel.Id })
    
    <div class="form-group">
        @Html.LabelFor(m => m.IndividualExpenseFormModel.Date, new { @class = "col-md-4 control-label" })
        <div class="col-md-8">
            @Html.TextBoxFor(m => m.IndividualExpenseFormModel.Date, new { @class = "form-control bt-datetimepicker", @Value = Model.IndividualExpenseFormModel.Date })
            @Html.ValidationMessageFor(m => m.IndividualExpenseFormModel.Date, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.IndividualExpenseFormModel.Category, new { @class = "col-md-4 control-label" })
        <div class="col-md-8">
            @Html.DropDownListFor(m => m.IndividualExpenseFormModel.Category, Model.CategoryList, new { @class = "form-control", type = "Number", @Value = Model.IndividualExpenseFormModel.Category })
            @Html.ValidationMessageFor(m => m.IndividualExpenseFormModel.Category, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.IndividualExpenseFormModel.ItemName, new { @class = "col-md-4 control-label" })
        <div class="col-md-8">
            @Html.TextBoxFor(m => m.IndividualExpenseFormModel.ItemName, new { @class = "form-control", @Value = Model.IndividualExpenseFormModel.ItemName })
            @Html.ValidationMessageFor(m => m.IndividualExpenseFormModel.ItemName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.IndividualExpenseFormModel.ItemPrice, new { @class = "col-md-4 control-label" })
        <div class="col-md-8">
            @Html.TextBoxFor(m => m.IndividualExpenseFormModel.ItemPrice, new { @class = "form-control", type = "Number", @Value = Model.IndividualExpenseFormModel.ItemPrice })
            @Html.ValidationMessageFor(m => m.IndividualExpenseFormModel.ItemPrice, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.IndividualExpenseFormModel.Notes, new { @class = "col-md-4 control-label" })
        <div class="col-md-8">
            @Html.TextAreaFor(m => m.IndividualExpenseFormModel.Notes, new { @class = "form-control", @Value = Model.IndividualExpenseFormModel.Notes })
            @Html.ValidationMessageFor(m => m.IndividualExpenseFormModel.Notes, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-4 col-md-8">
            <input type="submit" value="Submit" class="btn btn-primary" />
        </div>
    </div>
}

TimeMachine/Views/IndividualExpense/ViewExpenseHistory.cshtml
@model TimeMachine.Models.IndividualExpenseDetailViewModel

<div>
    <h4>View Your Transactions</h4>
</div>
<hr />

<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>Date</th>
            <th>Item</th>
            <th>Price</th>
            <th>Comments</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var row in Model.IndividualExpenseHistoryModel)
        {
            <tr>
                <td>@row.Date</td>
                <td>@row.ItemName</td>
                <td>@row.ItemPrice</td>
                <td>@row.Notes</td>
                <td>@Html.ActionLink("Edit", "EditHistoryItem", "IndividualExpense", new { id = row.Id }, "")</td>
                <td>@Html.ActionLink("Delete", "DeleteHistoryItem", new { id = row.Id }, new { onclick = "return ConfirmDelete()" })</td>
            </tr>
        }
    </tbody>
</table>